import MacroTesting
import Testing
import SplatMacros

@testable import Splat

@Suite(.serialized)
struct SplatTests {

    @Test func `basic splat`() {
        withMacroTesting(macros: ["Splat": SplatMacro.self]) {
            assertMacro {
                """
                @Splat
                struct Person {
                    let arguments: Arguments

                    init(_ arguments: Arguments) {
                        self.arguments = arguments
                    }

                    struct Arguments {
                        let name: String
                        let age: Int
                    }
                }
                """
            } expansion: {
                """
                struct Person {
                    let arguments: Arguments

                    init(_ arguments: Arguments) {
                        self.arguments = arguments
                    }

                    struct Arguments {
                        let name: String
                        let age: Int
                    }

                    /// Convenience initializer that accepts Arguments properties as individual parameters.
                    ///
                    /// This initializer is generated by the `@Splat` macro to provide ergonomic
                    /// initialization without explicitly creating a Arguments instance.
                    public init(
                        `name`: String,
                        `age`: Int
                    )  {
                        self.init(Arguments(
                            `name`: `name`,
                            `age`: `age`
                        ))
                    }
                }
                """
            }
        }
    }

    @Test func `splat with throws`() {
        withMacroTesting(macros: ["Splat": SplatMacro.self]) {
            assertMacro {
                """
                @Splat
                struct Donor {
                    let arguments: Arguments

                    init(_ arguments: Arguments) throws {
                        self.arguments = arguments
                    }

                    struct Arguments {
                        let isAlive: Bool
                    }
                }
                """
            } expansion: {
                """
                struct Donor {
                    let arguments: Arguments

                    init(_ arguments: Arguments) throws {
                        self.arguments = arguments
                    }

                    struct Arguments {
                        let isAlive: Bool
                    }

                    /// Convenience initializer that accepts Arguments properties as individual parameters.
                    ///
                    /// This initializer is generated by the `@Splat` macro to provide ergonomic
                    /// initialization without explicitly creating a Arguments instance.
                    public init(
                        `isAlive`: Bool
                    ) throws {
                        try self.init(Arguments(
                            `isAlive`: `isAlive`
                        ))
                    }
                }
                """
            }
        }
    }

    @Test func `splat with typed throws`() {
        withMacroTesting(macros: ["Splat": SplatMacro.self]) {
            assertMacro {
                """
                @Splat
                struct Donor {
                    let arguments: Arguments

                    init(_ arguments: Arguments) throws(ValidationError) {
                        self.arguments = arguments
                    }

                    struct Arguments {
                        let isAlive: Bool
                    }

                    struct ValidationError: Error {}
                }
                """
            } expansion: {
                """
                struct Donor {
                    let arguments: Arguments

                    init(_ arguments: Arguments) throws(ValidationError) {
                        self.arguments = arguments
                    }

                    struct Arguments {
                        let isAlive: Bool
                    }

                    struct ValidationError: Error {}

                    /// Convenience initializer that accepts Arguments properties as individual parameters.
                    ///
                    /// This initializer is generated by the `@Splat` macro to provide ergonomic
                    /// initialization without explicitly creating a Arguments instance.
                    public init(
                        `isAlive`: Bool
                    ) throws(ValidationError) {
                        try self.init(Arguments(
                            `isAlive`: `isAlive`
                        ))
                    }
                }
                """
            }
        }
    }

    @Test func `splat with optional types`() {
        withMacroTesting(macros: ["Splat": SplatMacro.self]) {
            assertMacro {
                """
                @Splat
                struct Donor {
                    let arguments: Arguments

                    init(_ arguments: Arguments) throws {
                        self.arguments = arguments
                    }

                    struct Arguments {
                        let isAlive: Bool?
                        let isDeceased: Bool?
                    }
                }
                """
            } expansion: {
                """
                struct Donor {
                    let arguments: Arguments

                    init(_ arguments: Arguments) throws {
                        self.arguments = arguments
                    }

                    struct Arguments {
                        let isAlive: Bool?
                        let isDeceased: Bool?
                    }

                    /// Convenience initializer that accepts Arguments properties as individual parameters.
                    ///
                    /// This initializer is generated by the `@Splat` macro to provide ergonomic
                    /// initialization without explicitly creating a Arguments instance.
                    public init(
                        `isAlive`: Bool?,
                        `isDeceased`: Bool?
                    ) throws {
                        try self.init(Arguments(
                            `isAlive`: `isAlive`,
                            `isDeceased`: `isDeceased`
                        ))
                    }
                }
                """
            }
        }
    }

    @Test func `splat with custom names`() {
        withMacroTesting(macros: ["Splat": SplatMacro.self]) {
            assertMacro {
                """
                @Splat(propertyName: "state", structName: "State")
                struct Machine {
                    let state: State

                    init(_ state: State) {
                        self.state = state
                    }

                    struct State {
                        let isActive: Bool
                    }
                }
                """
            } expansion: {
                """
                struct Machine {
                    let state: State

                    init(_ state: State) {
                        self.state = state
                    }

                    struct State {
                        let isActive: Bool
                    }

                    /// Convenience initializer that accepts State properties as individual parameters.
                    ///
                    /// This initializer is generated by the `@Splat` macro to provide ergonomic
                    /// initialization without explicitly creating a State instance.
                    public init(
                        `isActive`: Bool
                    )  {
                        self.init(State(
                            `isActive`: `isActive`
                        ))
                    }
                }
                """
            }
        }
    }
}
